qld-gov-au/opswx-ckan-cookbook

.gitignore
README.md
attributes/ckan.rb
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb
templates/default/apache_ckan.conf.erb
templates/default/ckan_properties.ini.erb

use first domain in cloudformation opsworks list for site url, use rest as alias's, add extra email domain but default to public_tld if not set

Qol 5530 cloudfront corrects

---

recipes/httpd-configure.rb

- without this, OpsWorks doesn't actually issue the reload command

[QOL-5759] enable reload action on Apache service

---

recipes/solr-configure.rb
recipes/solr-shutdown.rb
templates/default/solr-healthcheck.sh.erb

- Each server creates a health check file on the EFS, named after itself and containing a timestamp of when it was last verified healthy (seconds since epoch).
This file is created on 'configure', updated via cron every minute unless manually deleted, and removed on shutdown.
Not yet used for anything, but will eventually serve as a method of coordinating master + slaves.

[QOL-4841] add health monitoring for Solr servers

---

recipes/solr-configure.rb
recipes/solr-deploy.rb
recipes/solr-shutdown.rb
templates/default/archive-solr-logs.sh.erb

Move Solr logs from `/var/solr/logs` (which is actually on the EFS) to `/var/log/solr`.

Qol 5833 move logs off efs

---

templates/default/ckan_properties.ini.erb

- CKAN doesn't have a definition for 'en' so it uses defaults, which are more like US English

[QOL-5604] use en_GB instead of en

---

templates/default/ckan_properties.ini.erb

- Datastore set-permissions script has bad effects on XLoader tables

[QOL-5831] have XLoader share the main database, not the datastore

---

recipes/solr-deploycore.rb

We want the `-u` flag, to unzip new files and freshen existing ones, not the `-f` flag, which doesn't unzip new ones.

[QOL-5350] drop undesirable unzip flag

---

templates/default/ckan_properties.ini.erb

- The default 'english' search often doesn't work properly, especially with non-standard words like scientific names

[QOL-5879] use 'simple' full-text search

---

templates/default/ckan_properties.ini.erb

- a lot of our most critical data uses non-ISO dates that can't be parsed without messytables anyway

[QOL-6190] put XLoader into compatibility mode for easier migration

---

templates/default/apache_ckan.conf.erb

- this will allow us to lock down the user list API to authorised users

[QOL-5710] allow cookie-based authentication for autocomplete APIs

---

files/default/supervisor-ckan-worker.conf

With this change, we will be able to use commands like `sudo supervisorctl restart ckan-worker:ckan-worker-00` to restart the individual worker, instead of having to restart the entire Supervisor process.

[QOL-6483] add Unix socket config so that supervisorctl works

---

recipes/ckanweb-efs-setup.rb
recipes/ckanweb-setup.rb
recipes/nginx-efs-setup.rb
recipes/nginx-setup.rb

Testing on test.data.qld.gov.au showed that there were error scenarios around creating new servers, eg trying to stop supervisor processes via a socket that didn't yet exist, trying to create directories owned by an account that didn't yet exist, etc.

Qol 6681 fix disk setup

---

templates/default/apache_ckan.conf.erb

Redirect all known language codes to plain URLs. Incorporates currently-supported translations plus potential future ones based on https://www.science.co.il/language/Locale-codes.php

Qol 6710 localisation errors

---

templates/default/apache_ckan.conf.erb

- need to have the same number of replacement groups on all branches
- also simplify the regex by consistently handling all region specifiers (eg en_AU, en_UK) for each language

[QOL-6710] drop regex groups since they interfere with the replacement

---

templates/default/ckan_properties.ini.erb

Needed for Public Trust to upload their "unclaimed money" data.

[QOL-7007] increase resource size limit to 250MB

---

files/default/supervisor-ckan-harvest-fetch.conf
files/default/supervisor-ckan-harvest-gather.conf

The docs don't say to use it, and it seems to interfere with proper shutdown of the fetch consumer

[DQL2-13] don't specify the 'stopwaitsecs' property

---

recipes/ckanweb-setup.rb

- otherwise we sometimes get orphaned duplicate processes

[DQL2-13] ensure that Supervisor-managed processes are stopped

---

.gitignore
files/default/supervisor-ckan-archiver.conf
recipes/ckanweb-deploy-exts.rb
templates/default/ckan_properties.ini.erb

Here’s the minimum requirements for adding the QA/5 Star related extensions to the cookbook & infrastructure:
Extensions
http://github.com/okfn/ckanext-qa.git - we will need to fork this to apply custom scoring rules around validated resources, so might as well fork it now into qld-gov-au and we’ll fork from there.
http://github.com/datagovuk/ckanext-report.git
http://github.com/ckan/ckanext-archiver.git
Neither of those two use releases/tags, so just point to master branch.
CKAN ini file changes
ckan.plugins = ...  qa archiver report
(in that specific order)
ckanext-archiver.archive_dir = /app/filestore/archive
ckanext-archiver.cache_url_root = http://dataqld-ckan.docker.amazee.io/resources/
^ These two will need some experimenting in relation to your use of S3 uploads and their …

DQL2-6 enable db init, ordering and extra worker install

---

recipes/ckanweb-deploy.rb

- entries in '/etc/cron.d' are not supposed to be directly executable
This is causing error logs in DEV.

fix file permissions on cron script

---

attributes/ckan.rb
files/default/httpd-reload-on-low-memory
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb
recipes/default-configure.rb
recipes/httpd-configure.rb
recipes/nginx-configure.rb
recipes/solr-configure.rb
templates/default/apache_ckan.conf.erb

- Reduce WSGI processes per server to limit memory usage.
- Reload Apache if free memory is too low, in case of memory leaks.

Qol 7096 server restarts

---

recipes/ckanweb-deploy.rb
templates/default/ckan_properties.ini.erb

There is one CKAN config value you will need to add to your cookbook for the 5-star rating system deployment. Please update the extension file path to match your infrastructure setup.
qa.resource_format_openness_scores_json = /app/src/ckanext-data-qld/ckanext/data_qld/resource_format_openness_scores.json
This uses data-qld specific custom score rules for file formats and will need to be deployed with the qld-gov-au/ckanext-qa and qld-gov-au/ckanext-data-qld changes in the PRs.

Openess score config

---

recipes/ckanweb-deploy.rb

- Without this, we just rely on the initially generated metadata from 'master', which may not be correct.

[QOL-6815] ensure we use the correct CKAN egg metadata for our branch

---

recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb

- recognise version in source URL for CKAN extensions
- ensure that the version is stripped from the URL before appending another

clean up version extraction

---

templates/default/solr-sync.sh.erb

- force-local to make tar ignore colons
- missed a hyphen in the creation arguments

[QOL-7306] fix tar arguments for backing up to S3

---

files/default/updatedns
recipes/autoupdatedns.rb
recipes/ckanweb-setup.rb
recipes/datapusher-setup.rb
recipes/default-configure.rb
recipes/default.rb
recipes/nfs-setup.rb
recipes/postgres-setup.rb
recipes/solr-configure.rb
templates/default/solr-sync.sh.erb

This adjusts and repurposes the existing DNS configuration code to update it as needed each minute. It is capable of both automatic and manual failover between two Solr instances.
Caveats:
- The sync script only runs each minute. Changes made during this window may be lost, by being sent to a server that then becomes the secondary and gets overwritten before it can update the sync copy.
- The DNS primary/secondary configuration is not currently capable of having more than two servers in the pool. This might be resolvable by someone with more DNS expertise.
- Servers must use the same OpsWorks naming scheme, eg opendata-solr1, opendata-solr2. Current Open Data production has a misnamed legacy server, 'opendata-datapusher1'.

Qol 4841 Update DNS dynamically based on current primary

---

recipes/default-configure.rb

The extra swap space isn't available until disks are mounted, and isn't urgent at boot time, so it shouldn't be in /etc/fstab

Dc 18845 delay swap configuration until 'setup'

---

templates/default/solr-sync.sh.erb

- The Solr account might not have enough privileges to create the directory itself

[DC-18845] oops create the Solr backup directory as root and chown it

---

attributes/ckan.rb
files/default/squid.conf
recipes/ckanweb-configure.rb
recipes/squid-configure.rb
templates/default/ckan_properties.ini.erb

This will only affect extensions that support the 'ckan.download_proxy' property.

[QOL-6491] set up Squid proxy to block downloading from private addresses

---

templates/default/ckan_properties.ini.erb

- this still doesn't seem to be enough to actually serve objects from the Pairtree filestore,
but it will help support our new Paster command to get them into S3.

[QOL-7737] add config settings to support legacy Pairtree storage

---

files/default/allowed_functions.txt
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb
templates/default/ckan_properties.ini.erb

- only configure the whitelist if we're enabling the Datastore
- no need for uppercase entries since we're patching CKAN to treat the list as case-insensitive

[QOL-7841] clean up unnecessary function whitelisting config

---

recipes/solr-deploy.rb

- symlinks to logs can be inside the data directories, so copying the data directories first can overwrite log symlinks with the wrong paths and mess things up.

QOL-7857 move Solr logs before moving data

---

files/default/ckan_cli

This will work better with Supervisor, which doesn't handle grandchildren very gracefully.
Otherwise we get orphaned 'paster' processes, with ckan_cli stopped but paster still running.

[QOL-7934] remove our 'ckan_cli' helper from the process tree once it launches a child

---

resources/pip_install_app.rb

This doesn't affect already-installed eggs but is necessary on fresh installations.

[QOL-7857] handle HTTPS Git URLs as well as HTTP

---

templates/default/apache_ckan.conf.erb

This API doesn't have side effects, so it should be safe, and is needed for user activity stream infinite scrolling.
Also adjust regex syntax to ensure slashes are escaped if necessary, and optional API version numbers are always recognised.

[QOL-7891] allow 'user_activity_list_html' API to use auth cookies

---

templates/default/ckan_properties.ini.erb

Redirecting to the homepage loses the flash messages.

[QOL-7939] remain on reset page after requesting a password reset

---

templates/default/ckan_properties.ini.erb

Ideally we should replace the `organization_list` calls, but this is the most reliable fix for now.

[DC-22846] increase organisation list limit so our site isn't truncated

---

templates/default/pick-solr-master.sh.erb
templates/default/solr-healthcheck.sh.erb

Make Solr instances pass two health checks, not one, to become master, unless there is no viable candidate.

[QOL-8060] improve Solr failover reliability

---

templates/default/apache_ckan.conf.erb

- These will often be presigned S3 URLs, which are temporary and so shouldn't be indexed.
Even if they're not, the actual file download isn't the best option to index;
the resource page is the appropriate landing point.

[QOL-8104] stop robots from indexing resource download URLs

---

templates/default/ckan_properties.ini.erb

- we can update to the 'auto' ACL after successful deployment of the code to support it.
This gives better backward compatibility.

[QOL-8179] revert to private ACL

---

templates/default/ckan_properties.ini.erb

- We need to resolve the interaction between XLoader and the CloudFront cache before re-enabling.
XLoader is getting old file versions from CloudFront if they use public cacheable URLs.

[QOL-8179] revert ACL to private

---

templates/default/solr-healthcheck.sh.erb

- wrap commands in a subshell so we can grab the overall error code afterward.
The pipefail option is supposed to do this but doesn't seem to work.

[DC-27934][QOL-8406] preserve error codes

---

files/default/awslogs.conf
files/default/pick-solr-master.sh
files/default/solr-healthcheck.sh
files/default/solr-is-up.sh
files/default/solr-sync.sh
files/default/toggle-solr-healthcheck.sh
recipes/ckanbatch-configure.rb
recipes/solr-configure.rb
templates/default/solr-env.sh.erb

- Replace unrecoverable indexes offline instead of attempting online
- Run an integrity check on master index exports before pushing them to backups
- Refactor to reduce the number of files that need cookbook interpolation
- Expand swap size for batch servers so they hopefully don't crash during deployments.

QOL-8406 fix solr health checks

---

resources/pip_install_app.rb

- Exit early if key steps fail, like fetching the revision from the remote, or actually checking it out. Continue if minor steps fail, like 'git pull' failing when we're on a tag instead of a branch.
- Move cleanup steps into one place.

[QOL-8466] add error checking to app checkout

---

recipes/ckanbatch-deploy.rb

Archival script is populated from the wrong file, making it non-functional.

[QOL-8258] oops fix archival shell script

---

recipes/solr-deploy.rb

- update Log4J to 2.17.1 although we don't use the vulnerable JDBCAppender
- update the Log4J 1.x bridge although it's probably not vulnerable to anything by itself

[QOL-8500] extra patching just in case

---

files/default/solr-healthcheck.sh
files/default/solr-sync.sh
recipes/solr-configure.rb
recipes/solr-deploycore.rb

- Drop extra index integrity checks as they are causing collisions
- Don't manually tamper with index directory as it can race with current transactions
- Space out backup consumption more from backup export

QOL-8406 improve Solr health checks

---

files/default/pick-solr-master.sh

- Detect any Solr health checks present, regardless of hostname pattern, and up to any maximum number.

[QOL-8638] make Solr master election more robust

---

recipes/ckanbatch-configure.rb
templates/default/pick-job-server.sh.erb

- list heartbeat files alphabetically instead of trying to guess the names
- use heartbeat timestamps to determine whether a server is still active

[QOL-8576] improve logic for picking job master

---

templates/default/ckan-monitor-job-queue.sh.erb
templates/default/ckan_properties.ini.erb

Use full path for password reset landing page, so we don't go to /user/user/reset by mistake.

Develop to master

---

recipes/httpd-configure.rb
templates/default/clean-beaker-cache.sh.erb

- Beaker does not remove these by itself, causing the disk to fill with hundreds of thousands of small files.
They don't take up much space, but they endanger the half-million inode limit.

[DC-32168] add cron job to purge old Beaker session cache files

---

recipes/ckanweb-configure.rb
templates/default/ckan_properties.ini.erb
templates/default/clean-beaker-cache.sh.erb

- 'execdir' is safer on untrusted inputs, but opens a file descriptor each time, which crashes when operating on large numbers of files. In this case, we trust the inputs.

[DC-32168] use 'find -exec' instead of '-execdir'

---

attributes/ckan.rb
files/default/fix-dns.sh
recipes/ckan-deploy.rb
recipes/ckan-setup.rb
recipes/ckanbatch-setup.rb
recipes/ckanweb-deploy-exts.rb
recipes/datapusher-deploy.rb
recipes/datapusher-setup.rb
recipes/default.rb
resources/move_and_link.rb
resources/pip_install_app.rb
templates/default/ckan_properties.ini.erb

- Split package installation so we can install different versions according to what is available, eg 'postgresql94' vs just 'postgresql'.
- Install NPM manually if there isn't a suitable repo version.
- Combine duplicate CKAN config entries, which are now rejected by CKAN.
- Use a different CKAN group ID since the old one clashes with the new 'ec2-user' ID. NB Existing accounts will be unchanged.
- Handle both Python 2 and Python 3 paths.
- Handle systemd as an alternative to initd.
- Drop deprecated 'virtualenv' flag that is no longer supported under Python 3.

QOL-9055 prepare for Amazon Linux 2

---

recipes/ckanbatch-setup.rb
recipes/solr-deploy.rb

- Use an account ID that won't clash with new AMI
- Stop running Solr instances before modifying account
- Make detection of initd vs systemd more robust (don't rely on conditions that might change partway through execution)

QOL-9055 update Solr recipes to prepare for Amazon Linux 2

---

templates/default/ckan_properties.ini.erb

Once we adjust this, we'll be a step closer to the possibility of using vanilla XLoader instead of a fork.

[QOL-9159] use XLoader flag name consistent with upstream

---

recipes/solr-deploy.rb

- We need to update this when changing Solr account ID for Amazon Linux 2
- Allow ec2-user to have group access so it's easier to read files

[QOL-9055] ensure Solr log dir has correct permissions

---

recipes/solr-deploy.rb

- Use 'ps' built-in options instead of 'tail' so we can robustly handle empty output
- Fix shell loop syntax

QOL-9055 fix Solr shutdown syntax

---

files/default/updatedns

- Check whether alias record is already correct before submitting a change set
- Group related actions together and add more documentation comments
It's difficult to know what will help fix our intermittent DNS problems, but this should mean less unnecessary changes being submitted to Route53.

[DC-33331] make 'updatedns' more robust

---

files/default/ckan-uwsgi.ini
files/default/updatedns

Reduce unnecessary DNS changesets on Solr sync. This may help to avoid the occasional DNS-related incidents.

Develop to master - reduce Solr DNS noise

---

recipes/ckan-deploy.rb
recipes/ckanweb-deploy-exts.rb

- Make YTP Comments database setup compatible with Click
- Pin 'pyOpenSSL' to a version that supports the latest 'cryptography'.

QOL-9055 fix bugs

---

templates/default/nginx.conf.erb

- This is needed in order to make the datastore preview work on private datasets, and should be safe from CSRF since 'datastore_search' shouldn't have side effects.

[QOL-9341] allow cookies on the 'datastore_search' API

---

recipes/ckanweb-deploy-exts.rb

Repoze plugin uses a different Python path in CKAN 2.9; handle either one.

QOL-9385 login CSRF ckan 2.9

---

templates/default/ckan_properties.ini.erb

- We can set both the new and old flags (`use_type_guessing` and `just_load_with_messytables`), for compatibility.

[QOLDEV-347] set the new version of the XLoader type guessing flag

---

templates/default/ckan_properties.ini.erb

Update CKAN config to handle new XLoader
- Add the `use_type_guessing` flag as a replacement for `just_use_messytables`
- Retrieve an API token from SSM Parameter Store to authenticate jobs.

QOLDEV-347 Prepare for XLoader 0.12+

---

recipes/ckanweb-deploy.rb

- execdir needs an argument to specify whether to run once per file, or once for multiple files. Once per file is safer in this case, smaller scope for race conditions.

[QOLDEV-329] fix find syntax

---

recipes/ckanweb-deploy.rb

- The shell will consume semicolons if not quoted

[QOLDEV-329] escape execdir argument

---

recipes/ckanweb-deploy.rb

- Especially don't let it modify the Supervisor config that launches CKAN. This is important for preventing privilege escalations.

[QOLSVC-1866] don't allow CKAN to modify its own config

---

resources/pip_install_app.rb

- Recognise the CKAN minor version (eg 2.9) and check for a specific requirement file for that version (requirements-2.9.txt)
- Extend the py2 support to cover any Python major version, if a specific file exists

[QOLDEV-329] add support for CKAN-version-specific requirements files

---

templates/default/ckan_properties.ini.erb

Load keys from SSM (v2 key's).  per https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-recaptcha-publickey

QOLDEV-455 introduce recaptcha keys to ckan core

---

recipes/ckanweb-deploy-exts.rb

- Our templates should override any others.
In particular, ckanext-validation overrides the resource_view template without calling `super()`, so we need to get in first.

[CHDEXCHAE-60] move QGOV theme plugin to the top of the list

---

templates/default/ckan-email-notifications.sh.erb

- Add '--' to the revoke command, so that tokens starting with hyphens won't be mistakenly treated as options. See POSIX conventions guideline 10 at https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

[QOLDEV-517] fix token revocation edge case

---

templates/default/solr-env.sh.erb

- Solr 8 will restrict access to directories outside SOLR_HOME, so we need to either move backups there or specifically configure an exception

[QOLDEV-627] put Solr backup directory inside Solr home

---

templates/default/ckan_properties.ini.erb

- Data request notification functionality is moving into ckanext-datarequest, controlled by config, instead of being overridden by ckanext-data-qld.

[QOLDEV-638] add config flags to control data request notifications

---

templates/default/ckan_properties.ini.erb

so it can work with private resources that need auth to download

Include ckanext-validation-schema-generator api_key 

---

files/default/solr-sync.sh

- Drop the lock file before importing, to avoid Solr trying to load it like a segment.
- Make replication more robust in handling long export times.

QOLDEV-653 fix Solr replication errors

---

recipes/ckan-deploy.rb
recipes/ckanweb-deploy-exts.rb
templates/default/ckan_properties.ini.erb

Disable the core CSRF filter properly instead of conditionally injecting config in the wrong place.

QOLSVC-3914 fix logout CSRF tokens

---

files/default/solr-sync.sh
recipes/ckan-deploy.rb
recipes/ckanweb-deploy-exts.rb
templates/default/ckan_properties.ini.erb

Config to disable the CSRF filter was being injected into the config file in the wrong place, at the end of the logging configuration, and consequently did not work.

Develop to master - disable core CSRF filter properly

---

recipes/ckanweb-deploy-exts.rb

- Version 7.1.2 officially doesn't match Goodtables, but in practice it works. We don't use the Goodtables CLI anyway.

[QOLDEV-684] pin Click version to make Goodtables and Frictionless coexist

---

files/default/ckan_cli

- Redirect STDOUT to null before redirecting STDERR to STDOUT, otherwise STDERR stil points at the original STDOUT target (ie console)

[QOLDEV-684] adjust CLI order to properly hide STDERR

---

files/default/ckan_cli

- No point running a (slow) test for command name support if we don't have anything to act on

[QOLDEV-684] check for the presence of an underscore in Click command before trying it

---

files/default/ckan_cli
recipes/solr-deploy.rb

Fix the find command that is meant to exclude Solr snapshots from recursive ownership changes. Snapshots are ephemeral and thus do not need chown, and might disappear partway through attempting to apply it.

Develop to master - fix syntax for ignoring Solr snapshots

---

templates/default/ckan_properties.ini.erb

Also drop obsolete type-guessing flag.

enable XLoader's automatic datastore cleanup on resources that no longer qualify

---

recipes/nginx-configure.rb

- Handle existing log file expressions with or without a dot before the file extension. Failing to do so has resulted in log files not being rotated for years, and filling the disk.

[QOLSVC-4667] make logrotate config update more robust

---

resources/pip_install_app.rb
templates/default/ckan_properties.ini.erb

- Supplying the URL via custom JSON can result in it being frozen, but we need to manipulate it
- Also drop obsolete Recline plugin that will be removed in future versions

[QOLDEV-545] unfreeze app url string for modification if needed

---

recipes/ckan-deploy.rb
resources/ssm_lookup.rb

- No need to put passwords into our stack metadata when we can look them up from the server

[QOLDEV-545] look up sensitive values directly from SSM

---

recipes/solr-deploy.rb

- Filter paths with 'grep' instead of natively in 'find' to avoid complications with 'execdir' altering paths

[QOLDEV-545] restructure chown command to exclude snapshots

---

recipes/ckanweb-deploy-exts.rb
recipes/solr-deploycore.rb

- Make Solr restart more resilient to both old (initd) and new (systemd) management systems.
- Drop obsolete messytables patching (which results in an error when messytables was never installed).

QOLDEV-545 clean up cookbook for new servers

---

recipes/solr-deploycore.rb

- If Solr status check fails on both initd and systemd, assume it's already stopped and proceed

[QOLDEV-545] don't error if Solr can't be stopped

---

recipes/solr-deploycore.rb

Solr is intermittently hitting timeouts when started via systemd. Initd may be more reliable.
In the longer run we might benefit from moving it to Supervisord.

[QOLDEV-545] manage Solr exclusively via initd

---

files/default/supervisor-solr.conf

- Make Solr run in foreground so Supervisord can manage it
- Use the standard log file location

[QOLDEV-545] fix Solr supervisord config

---

recipes/ckanweb-deploy-exts.rb

- Typer 0.12+ relies on Click 8, which we aren't yet ready for

pin 'typer' library to avoid version clash

---

recipes/ckanparams.rb
recipes/stackparams.rb

- All servers need TLD to tag their disks, and site_name to archive their logs

[QOLDEV-545] move TLD and site_name parameters from ckanparams to stackparams

---

recipes/ckanparams.rb
recipes/ckanweb-deploy-exts.rb

Populating parameters has slightly different syntax depending on whether it's custom JSON or Parameter Store. Simpler to just look up from Parameter Store during deployment.

QOLDEV-545 look up plugin definitions just in time during deployment

---

recipes/stackparams.rb

This doesn't affect us while we're deploying to OpsWorks servers via Systems Manager, but it is needed for the decommission.

[QOLDEV-818] derive hostname from instance ID instead of expecting OpsWorks tag

---

recipes/ckanweb-deploy-exts.rb
resources/pip_install_app.rb

- Archiver needs to come after Report. QA needs to come after both. Geoscience Harvester needs to come after Harvester.
- Just push all the plugins that depend on others to the end of the list.

[QOLDEV-833] ensure plugins are installed in a viable order

---

recipes/ckan-configure.rb
recipes/ckan-deploy.rb
recipes/ckan-setup.rb
recipes/ckanbatch-configure.rb
recipes/ckanbatch-deploy.rb
recipes/ckanbatch-setup.rb
recipes/solr-configure.rb
recipes/solr-deploy.rb

'Configure' recipes should contain tasks that make an instance active, such as cron jobs and health check files. Other tasks go in setup/deploy.

QOLDEV-833 adjust recipes to better support 'warm' instances

---

recipes/ckanbatch-deploy.rb
recipes/ckanweb-deploy.rb
recipes/default-configure.rb
recipes/default.rb
recipes/solr-deploy.rb

- Wait until instance is meant to be active before starting services. This will help us set up instances for warm-standby, or as templates for generating golden AMIs.

[QOLDEV-833] only start Supervisor during 'configure' phase

---

recipes/stackparams.rb

Incorrect shell syntax was causing CIDR not to be populated.

QOLDEV-892 fix VPC ID variable syntax

---

recipes/default.rb

- Amazon Linux 2 still needs EPEL for eg Nginx

[QOLDEV-892] retain EPEL if it is present

---

recipes/ckanbatch-configure.rb
recipes/ckanweb-deploy-exts.rb

- We don't want to start workers before their code is fully installed.

QOLDEV-892 defer starting job workers until configure phase

---

recipes/ckanbatch-configure.rb
recipes/ckanweb-deploy-exts.rb

- We need to enable the worker units in order for systemctl to be aware of them

[QOLDEV-892] enable job workers on creation, just don't start them

---

recipes/default.rb
templates/default/aws-smtp-relay.erb

replaced v1 with v1.3.2 of aws smtp relay.
workaround put in place on current production system. IMDSv2 made optional (for now) and relay's restarted.

QOLSVC-6955 email issue IMDSv2 not compatible with aws smtp relay v1

---

recipes/default.rb
templates/default/aws-smtp-relay.erb

Version 1.3.2 encountered protocol errors.

[QOLSVC-6955] revert to SMTP relay 1.3.1 due to missing provider problem

---

recipes/default.rb
templates/default/aws-smtp-relay.erb

- This requires Java 21 but should fix dependency issues. Amazon Linux 2023 comes with Java 22 so we should be set.

[QOLSVC-6955] update SMTP relay to v2

---

files/default/solr-sync.sh
recipes/ckanbatch-configure.rb
recipes/solr-deploy.rb

- Import backups into secondary server(s) by stopping the server and wholesale replacing the index, rather than trying to dynamically import.
- Export backups as archives rather than exploded directories.
TODO Use S3 to pass backups, rather than EFS.

QOLDEV-863 Fix solr HA

---

files/default/solr-sync.sh
recipes/solr-deploy.rb

- Skip importing index archive if tar can't process it

[QOLDEV-863] ignore malformed Solr index archives

---

templates/default/ckan_properties.ini.erb

- ckanext-qgov already looks for the `urlm.app_path` property, we just haven't been setting it until now.

[QOLDEV-933] import PURL endpoint from SSM Parameter Store

---

templates/default/ckan_properties.ini.erb

- Don't wrap the whole string in double quotes. Comments can be quoted or bracketed.

[QOLSVC-7726] fix Archiver user agent string to comply with RFC 9110

---

templates/default/ckan_properties.ini.erb

- Private datasets can redirect to login, but deleted ones should give 404 so they can participate in PURL

[QOLDEV-933] return 404 on unauthorised requests for deleted datasets

---

recipes/ckanweb-deploy-exts.rb

- Retry up to 5 times if retrieval fails
- Provide fallback default value when appropriate

[QOLSVC-8441] make SSM parameter retrieval more robust

---

recipes/ckanweb-deploy-exts.rb

Reports are cached for several days, but once they expire, generating fresh ones (when the URL is visited) can take so long that errors are returned. Implementing a daily cron job should resolve this, keeping reports relatively fresh without end-user interaction.

[QOLSVC-5425] refresh reports each day

---

recipes/ckan-deploy.rb

- Plugins can add migration steps, so ensure we re-update the DB after configuring them

[QOLDEV-954] add a second DB upgrade step after plugins are enabled

---

recipes/ckanweb-deploy-exts.rb

Ensure the Datastore plugin has the chance to add the Data API button. Previously our theme was intercepting the template first and therefore had to re-add the button manually.

[QOLSVC-10616] move datastore forward in plugin order

---

files/default/ckan-uwsgi.ini
recipes/ckanweb-deploy-exts.rb

Use multiple processes instead of multiple threads to avoid threading-related issues.

QOLSVC-11279 work around threading-related errors

---

files/default/solr-import-backup.sh
files/default/solr-restore-from-backup.sh
files/default/solr-sync.sh
recipes/ckanbatch-configure.rb
recipes/solr-configure.rb
recipes/solr-deploy.rb

- Sync secondary servers from hourly S3 backup instead of every 5 minutes via EFS
- Run incremental rebuild hourly to fix any shortfall

[QOLSVC-10262] make Solr sync rely on S3 instead of EFS
