recipes/default.rb

- also provides a nice descriptive name for the console to use

[QOL-4680] tag EBS root volumes so we can manage them with AWS Backup

---

attributes/ckan.rb
files/default/supervisor-ckan-worker.conf
recipes/ckanweb-deploy.rb
recipes/ckanweb-setup.rb

- the validation extension will use this
- double installing to work around problems with the yum install

[DQL-60][QOL-5182] add worker to handle asynchronous CKAN jobs

---

recipes/ckanweb-deploy-exts.rb

- adding Google Analytics plugin broke the lookup

[DQL-72] [QOL-5251] fix theme plugin ordering

---

recipes/httpd-configure.rb
templates/default/ckan_properties.ini.erb
templates/default/nginx.conf.erb

- Fix robots.txt
- Fix Apache reload so it actually runs
- Use generic English locale

Develop to master

---

recipes/ckanweb-efs-setup.rb
recipes/default-configure.rb
recipes/httpd-efs-setup.rb

- local/bin is only populated during configure phase

[QOL-5833] oops keep using 'local/sbin' in setup phase for now

---

files/default/solr-log4j.properties
files/default/solr-logrotate
recipes/solr-configure.rb

- also update Log4J configuration to preserve more log files, since they're running out of rotation in less than a day

[QOL-6028] add Solr log rotation

---

templates/default/ckan_properties.ini.erb

Either ckanext-s3filestore or ckanext-cloudstorage. Unused config will just be ignored.

[QOL-5829] add CKAN config to handle S3 extensions

---

recipes/ckanweb-deploy-exts.rb

- this will help us to switch between forks and originals as needed

[QOL-5831] enable cookbook to switch Git remotes for CKAN extensions

---

recipes/ckanweb-deploy.rb

- handle Git app definition as an alternative to HTTP
- allow switching Git remotes
This will allow us to use a fork of CKAN when needed.

[QOL-6246] adjust CKAN deployment

---

templates/default/ckan_properties.ini.erb

- this affects user_show as well as user_list, which is likely a benefit.
However, it doesn't require special privileges, just login.

[QOL-5710] forbid anonymous access to user details

---

files/default/listhosts
files/default/monthly_backup
files/default/updateasg
files/default/updatedns
recipes/datapusher-shutdown.rb
recipes/default.rb
recipes/icinga-deploy.rb
recipes/nfs-shutdown.rb
recipes/solr-shutdown.rb
recipes/stackparams.rb
templates/default/ebs_backup.erb

- update AWS CLI to support it
- adjust direct metadata interactions to use token

[QOL-6491] use instance metadata service version 2

---

recipes/ckanweb-efs-setup.rb
recipes/efs-setup.rb
recipes/httpd-efs-setup.rb
recipes/solr-deploy.rb

- Apache, Nginx, and Solr at this point

[QOL-6681] move logs to extra EBS disk

---

recipes/ckanweb-configure.rb
recipes/ckanweb-deploy.rb
recipes/ckanweb-efs-setup.rb
recipes/nginx-configure.rb
recipes/solr-deploy.rb
recipes/solr-deploycore.rb

Also clean up service restarts.

[QOL-6681] move CKAN worker logs to extra disk

---

recipes/ckanweb-deploy-exts.rb
templates/default/ckan_properties.ini.erb

- Added `ckanext-ytp-comments` paster command `updatedb` - to add `deleted_by_user_id` column to `comment` table.
- Added CKAN `.ini` file setting `ckan.comments.show_comments_tab_page = True` to display dataset comments on separate tab.

[DQL-188] Dataset comments enhancements

---

files/default/supervisor-ckan-harvest-fetch.conf
files/default/supervisor-ckan-harvest-gather.conf
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb

- Added `supervisor-ckan-harvest-gather.conf` for harvest gather consumer background process
- Added `supervisor-ckan-harvest-fetch.conf` for harvest fetch consumer background process
- Copy harvest supervisor conf files in `/recipes/ckanweb-deploy.rb`
- Added ckanext-harvest `initdb` paster command to `recipes/ckanweb-deploy-exts.rb`
- Added ckanext-harvest `harvester run` cron job to `recipes/ckanweb-deploy.rb`
cc: @duttonw & @ThrawnCA

[DQL2-13] CKAN Harvest - Install and configure

---

files/default/supervisor-ckan-harvest-fetch.conf
files/default/supervisor-ckan-harvest-gather.conf
templates/default/ckan_properties.ini.erb

- [DQL2-13] Fix paster call for ckanext-harvest commands in supervisor config files
- [DQL2-31] Added CKAN .ini setting for enabling data request closing circumstances
@ThrawnCA

[DQL2] Cookbook fixes and addition

---

recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb

ensure we checkout the correct version the first time so pip install does not install metadata that is not correct

Versioning correctly

---

recipes/solr-configure.rb
templates/default/pick-solr-master.sh.erb
templates/default/solr-healthcheck.sh.erb
templates/default/toggle-solr-healthcheck.sh.erb

This is the next step toward automated Solr failover. Not complete yet, but should be backwards compatible.

Qol 4841 Add script to detect current Solr master

---

recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb

Also add more detail to installation messages.

oops fix version number stripping

---

recipes/default-configure.rb

This will help servers cope with load spikes gracefully. We can easily spare the disk space.

[QOL-7359] add 1GB swap disk to each server

---

recipes/default-configure.rb

- don't want to use a slash delimiter since the string to match is a path

[QOL-7359] oops add escape character to change sed delimiter

---

templates/default/ckan_properties.ini.erb

Update S3 URL to point at our own endpoint

Qol 7373 cloudfront s3

---

templates/default/ckan_properties.ini.erb

- keep the old parameter for backwards compatibility

[QOL-7373] update S3 parameter name for download proxy

---

files/default/fix-dns.sh
recipes/default-configure.rb
recipes/default.rb
recipes/solr-deploy.rb
templates/default/solr-sync.sh.erb

Still waiting for input on the root cause, but this should help somewhat to reduce the impact.

[DC-18845] automatically detect and try to recover from DNS failures

---

recipes/ckanweb-deploy-exts.rb

Not sure how this was missed, but should probably be folded in.

Chg 7814 hotfixes

---

files/default/ckan_cli
files/default/supervisor-ckan-archiver.conf
files/default/supervisor-ckan-harvest.conf
files/default/supervisor-ckan-worker.conf
recipes/ckan-deploy.rb
recipes/ckanbatch-deploy.rb
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb
recipes/ckanweb-maintenance.rb
templates/default/archiverTriggerAll.sh
templates/default/ckan-monitor-job-queue.sh.erb

- CKAN 2.9 replaces 'paster' with 'ckan' and has slightly different syntax.
This will detect whichever is present and call it appropriately.

Prepare for CKAN 2.9

---

recipes/ckan-configure.rb
recipes/ckanbatch-configure.rb
recipes/ckanweb-configure.rb
recipes/ckanweb-deploy-exts.rb

Open Data DEV is getting errors because running XLoader wipes the extra fields that ckanext-scheming expects.

[QOL-7857] install all extensions on batch nodes in case they alter batch processing

---

recipes/ckan-deploy.rb
recipes/ckan-setup.rb
recipes/ckanweb-efs-setup.rb
recipes/httpd-efs-setup.rb
recipes/nginx-efs-setup.rb
recipes/solr-deploy.rb
resources/move_and_link.rb

- Update virtualenv ownership even if virtualenv is a symlink
- Ensure ownership is updated before running other actions

Ensure virtual ownership is correct

---

recipes/solr-deploy.rb
resources/pip_install_app.rb

- don't put 'git+https' in the origin URL, just 'https'
- 'git clean' needs the -f flag to work

[QOL-7857] fix pip deployment steps

---

files/default/httpd-reload-on-low-memory

Don't restart to free up memory if we have over 1GB free

[DC-22275] fix Apache restart

---

templates/default/ckan_properties.ini.erb

- Grant public read to objects from publicly accessible datasets, revoke it for private datasets

[QOL-8179] automatically manage S3 object ACLs

---

templates/default/solr-healthcheck.sh.erb

- fix syntax errors
- export the index and run an integrity check

[DC-27934] improve Solr health check

---

recipes/default.rb
templates/default/solr-healthcheck.sh.erb
templates/default/solr-sync.sh.erb

- Improve health check so we test the index integrity, not just a ping.
- Avoid dangling 'index' symlinks that could get in the way.

Dc 27934 solr errors

---

templates/default/solr-healthcheck.sh.erb

Add features to automatically recover from index corruption.

DC-27934 Solr errors

---

templates/default/ckan_properties.ini.erb

- We have a fix at the s3filestore end now, to ensure we don't use stale cache after updating resources.

[QOL-8179] allow automatic ACL

---

recipes/ckanbatch-configure.rb
recipes/default.rb
templates/default/ckan_properties.ini.erb

- Increase swap space on batch servers to handle high load
- Move pip cache off root disk to avoid full disk problems
- Use SSM Parameter Store to control S3 ACL

Apply patches from hotfix branch

---

recipes/ckanweb-setup.rb

- This should resolve CVE-2021-44790 by dropping mod_lua.

[QOL-8537] drop unused Apache modules

---

recipes/solr-configure.rb

[QOL-8406] ensure that obsolete crontab entry from QOL-4841 is removed

---

recipes/ckanbatch-deploy.rb

- we eventually need an approach that is compatible with CKAN 2.9

[DC-28671] revert email notifications to 'paster post' for now

---

recipes/ckanbatch-deploy.rb
templates/default/ckan-email-notifications.sh.erb

- add a shell script that knows how to generate, use, and revoke an API token, so we can attach it to a curl request

[QOL-8576] handle CKAN 2.9 style email notifications

---

files/default/solr-sync.sh

Extend timeouts and improve error handling to cope with larger indexes as a result of the Geoscience Harvester.

QOL-8775 improve Solr health check robustness

---

recipes/ckanweb-setup.rb

- anything starting with 'php.'

[QOL-8537] disable more PHP config

---

files/default/solr-sync.sh

Clean up non-current backups on each sync.

Qol 8808 fix backup cleanup

---

recipes/solr-deploy.rb

- Output 'all but the first line' rather than 'the last line'

[QOL-9055] fix tail spec

---

recipes/ckan-configure.rb
recipes/ckanweb-deploy.rb

Only run chown/chmod on storage directories once.

CHG-12098 chmod cleanup

---

attributes/default.rb
recipes/ckanweb-shutdown.rb
recipes/swapfile.rb

Qol 9451 fix startup issues on small instances

---

recipes/ckanweb-deploy-exts.rb

Ensure openSSL python library is updated
fix whitespace on comments
remove cron when plugin is removed

QOLSVC-571 cookbook cleanup improvements

---

recipes/ckan-deploy.rb
templates/default/ckan_properties.ini.erb

Robustly handle features that are no longer present on CKAN 2.10

QOLSVC-978 CKAN 2.10 prep

---

files/default/solr-sync.sh
recipes/solr-configure.rb

- Increase export timeout
- Reduce export frequency
- Ensure cleanup still runs if export times out

QOLSVC-1823 fix cleanup of Solr exports

---

recipes/ckanweb-deploy-exts.rb

- Hyphens rather than underscores

[QOLDEV-327] fix Data Request command names

---

templates/default/ckan_properties.ini.erb

- dd/MM/yyyy rather than MM/dd/yyyy, etc

[QOLSVC-3115] set XLoader flag to use day-first date formats

---

templates/default/ckan-email-notifications.sh.erb
templates/default/ckan_properties.ini.erb

This has been tested on DEV and works correctly, parsing '02/08/2023' as the 2nd of August, not the 8th of February.

Develop to master - set XLoader day-first parsing flag

---

resources/pip_install_app.rb

- Run a pip install after checking out the target revision, to ensure we get the right metadata

[QOLSVC-978] ensure egg data is updated from the correct revision

---

templates/default/ckan_properties.ini.erb

- The previous default provider is no longer available

[QOLSVC-4126] configure the Spatial plugin, if present, to use QLD Globe

---

recipes/ckan-deploy.rb
recipes/ckanbatch-deploy.rb
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb
recipes/ckanweb-maintenance.rb
recipes/solr-deploy.rb
recipes/solr-deploycore.rb
recipes/stackparams.rb

- Still seeing occasional deployment failures from trying to chown ephemeral snapshot files

[QOLDEV-545] narrow Solr chown search path

---

attributes/ckan.rb
attributes/default.rb
recipes/stackparams.rb

Derive parameters from each other or from SSM Parameter Store

QOLDEV-545 clean up parameters that don't need to be passed in

---

recipes/ckanweb-deploy-exts.rb

- YAML will sometimes automatically convert 'yes' to true. Simplest solution is to accept any of the above.

[QOLDEV-545] accept various truthy values for the dsenable parameter

---

files/default/supervisor-ckan-uwsgi.conf
recipes/ckan-setup.rb
recipes/default.rb
recipes/solr-deploycore.rb
templates/default/ckan_properties.ini.erb

- Datastore relies on these. QOLDEV-749 has been raised to replace them.

[QOLDEV-545] restore Recline views for now

---

recipes/ckan-configure.rb
recipes/default-configure.rb

- Not just web and batch layers

[QOLDEV-545] reload Supervisord config as needed on all servers

---

recipes/ckanbatch-shutdown.rb
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-shutdown.rb
recipes/efs-setup.rb
recipes/solr-shutdown.rb

- Revision and URL were the wrong way around

[QOLDEV-545] swap SSM lookups

---

recipes/stackparams.rb

- Solr instances don't have access to most app-specific parameters

[QOLDEV-818] load internal zone TLD from the common parameter

---

recipes/ckan-deploy.rb
recipes/ckan-setup.rb
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb
recipes/ckanweb-setup.rb
recipes/default.rb
recipes/nginx-setup.rb
resources/pip_install_app.rb
templates/default/ckan_properties.ini.erb
templates/default/nginx.conf.erb

- Combine `pip install` and `yum install` commands when possible, and drop unnecessary calls, since they are slow.
- Also drop environment name from Nginx config filename.

QOLDEV-833 streamline cookbook for faster starts

---

recipes/ckanweb-deploy-exts.rb

- Need to inject the -e parameter before every URL

[QOLDEV-833] fix syntax for installing source instead of eggs

---

recipes/ckanbatch-configure.rb
recipes/ckanbatch-deploy.rb
recipes/ckanweb-configure.rb
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-deploy.rb
recipes/solr-configure.rb
recipes/solr-deploy.rb

Starting services too early results in errors.

QOLDEV-892 Wait for 'configure' phase to start services

---

recipes/default.rb

- Don't put in a cookbook condition, just make the command optional

[QOLDEV-892] simplify EPEL installation

---

recipes/ckan-deploy.rb
recipes/ckanbatch-deploy.rb
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-setup.rb
resources/pip_install_app.rb

- uv is much faster and caches better than pip

[QOLDEV-833] use 'uv' package manager for faster instance setup

---

recipes/ckan-deploy.rb
recipes/ckan-setup.rb

- uv is much faster and caches better than pip

[QOLDEV-833] install uv during setup not deploy

---

recipes/ckan-deploy.rb
recipes/ckan-setup.rb
recipes/ckanbatch-deploy.rb
recipes/ckanweb-deploy-exts.rb
recipes/ckanweb-setup.rb
resources/pip_install_app.rb

- uv is missing some features, like editable install from URL

[QOLDEV-833] revert from 'uv' to 'pip'

---

templates/default/ckan_properties.ini.erb

- We're interested in every status

[QOLDEV-988] enable all XLoader badges

---

templates/default/nginx.conf.erb

Hard-coding redirects in Nginx is much less flexible.

QOLDEV-1006 remove organisation redirects that should be handled by PURL

---

recipes/ckan-deploy.rb
recipes/ckanweb-deploy-exts.rb
templates/default/ckan_properties.ini.erb

- Drop obsolete changes to `who.ini` (Repoze.who is no longer used or necessary)
- Drop Recline plugins that are going away

QOLDEV-954 prepare for CKAN 2.11

---

recipes/ckanbatch-configure.rb
templates/default/archive-logs.sh.erb

This should help us recover better from out of hours failovers or other issues.

QOLDEV-833 add daily Solr reindex

---

recipes/ckanweb-configure.rb
recipes/ckanweb-deploy-exts.rb
templates/default/ckan_properties.ini.erb

- If ckanext-clamav is present, then install ClamAV.
- Ensure clamav plugin comes before s3filestore so it can scan uploads before they're processed

[QOLDEV-1137] add ckanext-clamav config

---

files/default/pick-solr-master.sh
files/default/solr-healthcheck.sh
files/default/solr-sync.sh

- Adding/removing of startup flags was not working correctly, restore old behaviour

[QOLDEV-863] revert startup file change

---

recipes/ckanweb-deploy-exts.rb
templates/default/ckan_properties.ini.erb

- Ensure Freshclam is installed
- Configure the Unix socket for the Clam daemon

[QOLDEV-1137] fix ClamAV config

---

files/default/solr-import-backup.sh
files/default/solr-restore-from-backup.sh
files/default/solr-sync.sh
recipes/solr-deploy.rb

- Allow automatic retrieval and import of the latest backup in one command

[QOLSVC-10984] improve scripts for manually restoring Solr

---

files/default/solr-import-backup.sh
files/default/solr-restore-from-backup.sh
recipes/ckanweb-deploy-exts.rb

Inject datastore plugin config before applying ordered plugins, so that ordering can take it into account.

QOLSVC-10616 fix plugin ordering
